#!/usr/bin/python
#
# Copyright 2024 Kaggle Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

# flake8: noqa
"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from kaggle.models.api_blob_type import ApiBlobType
from kaggle.models.collaborator import Collaborator
from kaggle.models.create_inbox_file_request import CreateInboxFileRequest
from kaggle.models.dataset_column import DatasetColumn
from kaggle.models.dataset_new_request import DatasetNewRequest
from kaggle.models.dataset_new_version_request import DatasetNewVersionRequest
from kaggle.models.dataset_update_settings_request import DatasetUpdateSettingsRequest
from kaggle.models.error import Error
from kaggle.models.kernel_push_request import KernelPushRequest
from kaggle.models.license import License
from kaggle.models.model_instance_new_version_request import ModelInstanceNewVersionRequest
from kaggle.models.model_instance_update_request import ModelInstanceUpdateRequest
from kaggle.models.model_new_instance_request import ModelNewInstanceRequest
from kaggle.models.model_new_request import ModelNewRequest
from kaggle.models.model_update_request import ModelUpdateRequest
from kaggle.models.result import Result
from kaggle.models.start_blob_upload_request import StartBlobUploadRequest
from kaggle.models.start_blob_upload_response import StartBlobUploadResponse
from kaggle.models.upload_file import UploadFile
