# coding: utf-8

"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kaggle
from kaggle.api.kaggle_api import KaggleApi  # noqa: E501
from kaggle.rest import ApiException


class TestKaggleApi(unittest.TestCase):
    """KaggleApi unit test stubs"""

    def setUp(self):
        self.api = kaggle.api.kaggle_api.KaggleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_competitions_data_download_file(self):
        """Test case for competitions_data_download_file

        Download competition data file  # noqa: E501
        """
        pass

    def test_competitions_data_list_files(self):
        """Test case for competitions_data_list_files

        List competition data files  # noqa: E501
        """
        pass

    def test_competitions_list(self):
        """Test case for competitions_list

        List competitions  # noqa: E501
        """
        pass

    def test_competitions_submissions_list(self):
        """Test case for competitions_submissions_list

        List competition submissions  # noqa: E501
        """
        pass

    def test_competitions_submissions_submit(self):
        """Test case for competitions_submissions_submit

        Submit to competition  # noqa: E501
        """
        pass

    def test_competitions_submissions_upload(self):
        """Test case for competitions_submissions_upload

        Upload competition submission file  # noqa: E501
        """
        pass

    def test_competitions_submissions_url(self):
        """Test case for competitions_submissions_url

        Generate competition submission URL  # noqa: E501
        """
        pass

    def test_datasets_download_file(self):
        """Test case for datasets_download_file

        Download dataset file  # noqa: E501
        """
        pass

    def test_datasets_list(self):
        """Test case for datasets_list

        List datasets  # noqa: E501
        """
        pass

    def test_datasets_list_files(self):
        """Test case for datasets_list_files

        List dataset files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
